document.write("<table width=\"778\" border=\"0\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\">");
document.write("<tr><td width=\"1\" valign=\"top\" bgcolor=\"#E0E0E0\">");
document.write("<img src=\"/ananda/img/1x1.gif\" width=\"1\" height=\"1\" /></td>");
document.write("<td valign=\"top\">");
document.write("<img src=\"/img/learner.gif\" width=\"175\" height=\"152\" border=\"0\" usemap=\"#Map2\" /></td>");
document.write("<td width=\"602\" valign=\"top\">");
document.write("<object classid=\"clsid:D27CDB6E-AE6D-11cf-96B8-444553540000\" codebase=\"http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=7,0,19,0\" width=\"602\" height=\"152\">");
document.write("<param name=\"movie\" value=\"/swf/learner.swf\" />");
document.write("<param name=\"quality\" value=\"high\" />");
document.write("<embed src=\"/swf/learner.swf\" quality=\"high\" pluginspage=\"http://www.macromedia.com/go/getflashplayer\" type=\"application/x-shockwave-flash\" width=\"602\" height=\"152\"></embed>");
document.write("</object></td></tr></table>");
document.write("<table width=\"780\" border=\"0\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\"><tr>");
document.write("<td width=\"1\" valign=\"top\" bgcolor=\"#E0E0E0\">");
document.write("<img src=\"/img/green_dot.gif\" width=\"1\" height=\"1\" /></td>");
document.write("<td valign=\"top\"><table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">");
document.write("<tr><td valign=\"middle\" bgcolor=\"#0090EC\">");
document.write("<img src=\"/ananda/img/1x1.gif\" width=\"174\" height=\"1\" /></td>");
document.write("<td valign=\"top\"></td>");
document.write("<td valign=\"top\" bgcolor=\"#68169C\">");
document.write("<img src=\"/ananda/img/1x1.gif\" width=\"174\" height=\"1\" /></td>");
document.write("<td valign=\"top\"></td>");
document.write("<td valign=\"top\" bgcolor=\"#DF6400\">");
document.write("<img src=\"/ananda/img/1x1.gif\" width=\"174\" height=\"1\" /></td>");
document.write("<td valign=\"top\"></td>");
document.write("<td valign=\"top\" bgcolor=\"#9C163B\">");
document.write("<img src=\"/ananda/img/1x1.gif\" width=\"174\" height=\"1\" /></td>");
document.write("<td valign=\"top\"></td>");
document.write("<td valign=\"top\" bgcolor=\"#363A90\"></td>");
document.write("</tr><tr>");
document.write("<td width=\"174\" height=\"40\" valign=\"middle\" bgcolor=\"#999933\">");
document.write("<table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">");
document.write("<tr><td width=\"10\" height=\"5\" valign=\"top\"></td>");
document.write("<td ></td></tr><tr><td>&nbsp;</td>");
document.write("<td valign=\"top\"><font class=\"global_nav\">");
document.write("<a href=\"/common/learner/learner.html\" class=\"global_nav\">SIS</a>");
document.write("</font></td>");
document.write("</tr><tr><td height=\"5\" valign=\"top\"></td><td></td></tr></table></td>");
document.write("<td width=\"1\" valign=\"top\"><img src=\"/img/1x1.gif\" width=\"1\" height=\"1\" />");
document.write("</td>");
document.write("<td width=\"174\" valign=\"middle\" bgcolor=\"#68169C\">");
document.write("<table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">");
document.write("<tr><td width=\"10\" height=\"5\" valign=\"top\"></td>");
document.write("<td ></td></tr><tr><td>&nbsp;</td>");
document.write("<td valign=\"top\"><font class=\"global_nav\">");
document.write("<a href=\"/common/curriculum/curriculum.html\" class=\"global_nav\">Curriculum</a></font></td>");
document.write("</tr><tr><td height=\"5\" valign=\"top\"></td><td></td></tr></table></td>");
document.write("<td width=\"1\" valign=\"top\"><img src=\"/img/1x1.gif\" width=\"1\" height=\"1\" />");
document.write("</td><td width=\"174\" valign=\"middle\" bgcolor=\"#DF6400\">");
document.write("<table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">");
document.write("<tr><td width=\"10\" height=\"5\" valign=\"top\"></td>");
document.write("<td ></td></tr><tr><td>&nbsp;</td>");
document.write("<td valign=\"top\"><font class=\"global_nav\">");
document.write("<a href=\"/common/parents/parents.html\" class=\"global_nav\">Parents</a></font></td>");
document.write("</tr><tr><td height=\"5\" valign=\"top\"></td><td></td></tr></table></td>");
document.write("<td width=\"1\" valign=\"top\"><img src=\"/img/1x1.gif\" width=\"1\" height=\"1\" />");
document.write("</td>");
document.write("<td width=\"174\" valign=\"middle\" bgcolor=\"#9C163B\">");
document.write("<table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">");
document.write("<tr><td width=\"10\" height=\"5\" valign=\"top\"></td><td ></td>");
document.write("</tr><tr><td>&nbsp;</td>");
document.write("<td valign=\"top\"><font class=\"global_nav\">");
document.write("<a href=\"/common/mentor/mentor.html\" class=\"global_nav\">Mentor</a></font></td>");
document.write("</tr><tr><td height=\"5\" valign=\"top\"></td><td></td></tr></table></td>");
document.write("<td width=\"1\" valign=\"top\"><img src=\"/img/1x1.gif\" width=\"1\" height=\"1\" />");
document.write("</td><td align=\"center\" valign=\"middle\" bgcolor=\"#363A90\">");
document.write("<img src=\"/img/home_logo.gif\" width=\"55\" height=\"34\" border=\"0\" usemap=\"#MapMap\"/></td>");
document.write("</tr></table>");
document.write("</td><td width=\"1\" valign=\"top\" bgcolor=\"#E0E0E0\">");
document.write("<img src=\"/img/green_dot.gif\" width=\"1\" height=\"1\" /></td>");
document.write("</tr></table>");