<%@ page contentType="text/html; charset=iso-8859-1" language="java" import="java.sql.*"  %>
<%@ taglib uri="http://jakarta.apache.org/taglibs/image-1.0" prefix="img" %>

<html>
<head>
<title>Image Tag examples</title>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
</head>

<body>
<h1 align="center">Image Tag examples</h1>
<table width="100%" border="0" cellpadding="2">
  <tr align="center"> 
    <td colspan="3"><h2>Example 1:</h2> <b>Saved within the context and accessed as a static image</b></td>
  </tr>
  <tr> 
    <td>&nbsp;</td>
    <td align="center">&nbsp;
    
<img:image src="miku1.jpg"
        dir="generated"
        name="splash-new-miku.jpg"
		refresh="true"
	  attributes="border='0' alt='a sample dynamic image'">
  <img:resize scale="10%" />
	<img:text text="Saved within the context"
		x="10%" 
		y="75%" 
		font="Arial" 
		bold="true" 
		size="14" 
		color="0x0000ff"
	/>
</img:image>    
  
    </td>
    <td>&nbsp;</td>
  </tr>

  <tr align="center"> 
    <td colspan="3"><hr/></td>
  </tr>

  <tr align="center"> 
    <td colspan="3"><h2>Example 2:</h2> <b>Saved in the context temp dir and streamed by a servlet</b></td>
  </tr>
  <tr> 
    <td>&nbsp;</td>
    <td align="center">&nbsp;
    
<img:image src="/images/splash.jpg"
        name="splash-new-gray.jpg"
	  attributes="border='0' alt='a sample dynamic image'">
    <img:grayscale/>
    <img:overlay x="55%" y="50%">
        <img:image src="/images/new.gif" >
            <img:rotate degrees="-30" />
            <img:resize scale="80%" />
            <img:transparency level="125" />
        </img:image>        
    </img:overlay>
    <img:border width="5" height="3" 
            color="0x005d00"/>
    <img:resize bestfit="true" width="200" height="400"/>
    <img:text text="Saved in the context temp dir"
		x="10%" 
		y="75%" 
		font="Arial" 
		bold="true" 
		size="12" 
		color="0xff0000"
	/>    
</img:image>    
  
    </td>
    <td>&nbsp;</td>
  </tr>
  <tr> 
    <td align="right">&nbsp;<!--Previous&nbsp;&lt;&lt;--></td>
    <td width="100%" align="left">
	
	
		<blockquote> 
		  Overlay a Rotated transparent image on a Grayscaled image and then Resize 
		    it (GIF on JPEG). 
		  <pre>
&lt;img:image src=&quot;/images/splash.jpg&quot;
        name=&quot;splash-new-gray.jpg&quot;
        attributes=&quot;border='0' alt='a sample dynamic image'&quot;&gt;
    &lt;img:grayscale/&gt;
    &lt;img:overlay x=&quot;55%&quot; y=&quot;60%&quot;&gt;
        &lt;img:image src=&quot;/images/new.gif&quot; &gt;
            &lt;img:rotate degrees=&quot;-30&quot; /&gt;
            &lt;img:resize scale=&quot;80%&quot; /&gt;
            &lt;img:transparency level=&quot;125&quot; /&gt;            
        &lt;/img:image&gt;        
    &lt;/img:overlay&gt;
    &lt;img:border width=&quot;5&quot; height=&quot;3&quot; 
            color=&quot;0x005d00&quot;/&gt;
    &lt;img:resize bestfit=&quot;true&quot; width=&quot;200&quot; height=&quot;400&quot;/&gt;
    &lt;img:text text=&quot;Saved in the context temp dir&quot;
		x=&quot;10%&quot; 
		y=&quot;75%&quot; 
		font=&quot;Arial&quot; 
		bold=&quot;true&quot; 
		size=&quot;12&quot; 
		color=&quot;0xff0000&quot;
	/&gt;
&lt;/img:image&gt;
		</pre>		
		The sequence of operations to generate the output image: -
		<ol>
		  <li>The image file &quot;splash.jpg&quot; is loaded the first time this tag/ page is accessed
                (to load it each time the &quot;refresh&quot; must be set to &quot;true&quot;). 
                Otherwise it checks if &quot;splash-new-gray.jpg&quot; is in the context's temp directory. </li>
		  <li>The image is converted to grayscale. </li>
		  <li>The "new.gif" is overlaid/ painted on the base image at location 5% right 
		    and 60% below (percentages of base image's current &quot;width&quot; and &quot;height&quot; 
		    respectively) the top-left corner. The image for overlay is generated by the following steps: - </li>
		    <ol>
		    	<li>The nested image tag loads the &quot;new.gif&quot;</li>
		    	<li>The image is rotated by &quot;-30&quot; degrees</li>
		    	<li>The resulting image is resize/scaled to its &quot;80%&quot;</li>
		    </ol>
		  <li>A colored border with &quot;5&quot; pixels thickness at the sides and &quot;3&quot; pixels at the top
		   and bottom is added. </li>	
		  <li>The whole image is resized/ scaled to fit within a &quot;200&quot; x &quot;400&quot; rectangle. </li>  
		  <li>The image is saved as &quot;splash-new-gray.jpg&quot; in the &quot;generated&quot; 
		  directory. </li>
		  <li>An <code>&lt;img&gt;</code> tag similar to <code>&lt;img border='0' alt='a sample dynamic image' 
                src=&quot;/image-examples/gen-image/splash-new-gray.jpg&quot; width=&quot;200&quot; height=&quot;132&quot;&gt;</code> 
                is written. The &quot;width&quot; and &quot;height&quot; are that of the resulting image.</li>
		</ol>
		</blockquote>	

	</td>
    <td>&nbsp;<!--&gt;&gt;&nbsp;Next--></td>
  </tr>
</table>
<p align="center">
	<b>Source Images used in the above example:-</b><br/>
	<img src="images/splash.jpg" /><br/><br/>
	<img src="images/new.gif" />
</p>
</body>
</html>
