/*
 * JSP generated by Resin-3.0.8 (built Tue, 08 Jun 2004 02:25:40 PDT)
 */

package _jsp;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;

public class _image__jsp extends com.caucho.jsp.JavaPage{
  private boolean _caucho_isDead;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    javax.servlet.http.HttpSession session = request.getSession(true);
    com.caucho.server.webapp.Application _jsp_application = _caucho_getApplication();
    javax.servlet.ServletContext application = _jsp_application;
    com.caucho.jsp.PageContextImpl pageContext = com.caucho.jsp.QJspFactory.allocatePageContext(this, _jsp_application, request, response, null, session, 8192, true);
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    response.setContentType("text/html");
    org.apache.taglibs.image.ImageTag _jsp_ImageTag_0 = null;
    org.apache.taglibs.image.ResizeTag _jsp_ResizeTag_1 = null;
    org.apache.taglibs.image.TextTag _jsp_TextTag_2 = null;
    org.apache.taglibs.image.ResizeTag _jsp_ResizeTag_3 = null;
    org.apache.taglibs.image.OverlayTag _jsp_OverlayTag_4 = null;
    org.apache.taglibs.image.ImageTag _jsp_ImageTag_5 = null;
    org.apache.taglibs.image.ResizeTag _jsp_ResizeTag_6 = null;
    org.apache.taglibs.image.ImageTag _jsp_ImageTag_7 = null;
    org.apache.taglibs.image.ResizeTag _jsp_ResizeTag_8 = null;
    org.apache.taglibs.image.TextTag _jsp_TextTag_9 = null;
    try {
      out.write(_jsp_string0, 0, _jsp_string0.length);
      com.caucho.jsp.BodyContentImpl _jsp_endTagHack0 = null;
      if (_jsp_ImageTag_0 == null) {
        _jsp_ImageTag_0 = new org.apache.taglibs.image.ImageTag();
        _jsp_ImageTag_0.setPageContext(pageContext);
        _jsp_ImageTag_0.setParent((javax.servlet.jsp.tagext.Tag) null);
        _jsp_ImageTag_0.setSrc("/miku1.jpg");
        _jsp_ImageTag_0.setDir("generated");
        _jsp_ImageTag_0.setRefresh(true);
        _jsp_ImageTag_0.setAttributes("border='0' alt='a sample dynamic image'");
      }

      _jsp_ImageTag_0.setName("new-miku-20.jpg");
      _jsp_ImageTag_0.setQuality((float) 0.1);
      int _jspEval2 = _jsp_ImageTag_0.doStartTag();
      if (_jspEval2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        out = pageContext.pushBody();
        _jsp_endTagHack0 = (com.caucho.jsp.BodyContentImpl) out;
        _jsp_ImageTag_0.setBodyContent(_jsp_endTagHack0);
        out.write(_jsp_string1, 0, _jsp_string1.length);
        if (_jsp_ResizeTag_1 == null) {
          _jsp_ResizeTag_1 = new org.apache.taglibs.image.ResizeTag();
          _jsp_ResizeTag_1.setPageContext(pageContext);
          _jsp_ResizeTag_1.setParent((javax.servlet.jsp.tagext.Tag) _jsp_ImageTag_0);
          _jsp_ResizeTag_1.setWidth("160");
          _jsp_ResizeTag_1.setBestfit(false);
        }

        _jsp_ResizeTag_1.doEndTag();
        out.write(_jsp_string2, 0, _jsp_string2.length);
        if (_jsp_TextTag_2 == null) {
          _jsp_TextTag_2 = new org.apache.taglibs.image.TextTag();
          _jsp_TextTag_2.setPageContext(pageContext);
          _jsp_TextTag_2.setParent((javax.servlet.jsp.tagext.Tag) _jsp_ImageTag_0);
          _jsp_TextTag_2.setText("Shree Bhattacharyya - image width height%");
          _jsp_TextTag_2.setX("10%");
          _jsp_TextTag_2.setY("75%");
          _jsp_TextTag_2.setFont("Arial");
          _jsp_TextTag_2.setBold(true);
          _jsp_TextTag_2.setSize(14);
          _jsp_TextTag_2.setColor("0x0000ff");
        }

          _jsp_TextTag_2.setBodyContent((javax.servlet.jsp.tagext.BodyContent) null);
        _jsp_TextTag_2.doEndTag();
        out.write(_jsp_string3, 0, _jsp_string3.length);
        _jsp_ImageTag_0.doAfterBody();
        out = pageContext.popBody();
      }
      _jsp_ImageTag_0.doEndTag();
      if (_jsp_endTagHack0 != null) {
        pageContext.releaseBody(_jsp_endTagHack0);
        _jsp_endTagHack0 = null;
      }
      out.write(_jsp_string4, 0, _jsp_string4.length);
       int pid =3;
out.println("<img:image src=\"/group_photo/3/"+pid+"jpg\"");
        out.println("dir=\"generated/group_photo/3/"+pid+".jpg\"");
        out.println("name=\"3.jpg\"");
		out.println("refresh=\"true\"");
		out.println("quality=\"0.8\"");
	  out.println("attributes=\"border='0' alt='a sample dynamic image'\">");
  out.println("<img:resize width=\"160\"  bestfit=\"yes\" />");
	out.println("<img:text text=\"IWS\"");
out.println("x=\"10%\" y=\"75%\" font=\"Arial\" bold=\"true\" size=\"14\" color=\"0x0000ff\"/>");
out.println("</img:image>");

      out.write(_jsp_string5, 0, _jsp_string5.length);
      com.caucho.jsp.BodyContentImpl _jsp_endTagHack12 = null;
      if (_jsp_ImageTag_0 == null) {
        _jsp_ImageTag_0 = new org.apache.taglibs.image.ImageTag();
        _jsp_ImageTag_0.setPageContext(pageContext);
        _jsp_ImageTag_0.setParent((javax.servlet.jsp.tagext.Tag) null);
        _jsp_ImageTag_0.setSrc("/miku1.jpg");
        _jsp_ImageTag_0.setDir("generated");
        _jsp_ImageTag_0.setRefresh(true);
        _jsp_ImageTag_0.setAttributes("border='0' alt='a sample dynamic image'");
      }

      _jsp_ImageTag_0.setName("new-miku-10.jpg");
      _jsp_ImageTag_0.setQuality((float) 1.0);
      int _jspEval14 = _jsp_ImageTag_0.doStartTag();
      if (_jspEval14 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        out = pageContext.pushBody();
        _jsp_endTagHack12 = (com.caucho.jsp.BodyContentImpl) out;
        _jsp_ImageTag_0.setBodyContent(_jsp_endTagHack12);
        out.write(_jsp_string1, 0, _jsp_string1.length);
        if (_jsp_ResizeTag_3 == null) {
          _jsp_ResizeTag_3 = new org.apache.taglibs.image.ResizeTag();
          _jsp_ResizeTag_3.setPageContext(pageContext);
          _jsp_ResizeTag_3.setParent((javax.servlet.jsp.tagext.Tag) _jsp_ImageTag_0);
          _jsp_ResizeTag_3.setScale("10%");
        }

        _jsp_ResizeTag_3.doEndTag();
        out.write(_jsp_string6, 0, _jsp_string6.length);
        com.caucho.jsp.BodyContentImpl _jsp_endTagHack19 = null;
        if (_jsp_OverlayTag_4 == null) {
          _jsp_OverlayTag_4 = new org.apache.taglibs.image.OverlayTag();
          _jsp_OverlayTag_4.setPageContext(pageContext);
          _jsp_OverlayTag_4.setParent((javax.servlet.jsp.tagext.Tag) _jsp_ImageTag_0);
          _jsp_OverlayTag_4.setX("5%");
          _jsp_OverlayTag_4.setY("90%");
          _jsp_OverlayTag_4.setColor("0xffffff");
          _jsp_OverlayTag_4.setTolerance(35);
        }

        int _jspEval21 = _jsp_OverlayTag_4.doStartTag();
        if (_jspEval21 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          out = pageContext.pushBody();
          _jsp_endTagHack19 = (com.caucho.jsp.BodyContentImpl) out;
          _jsp_OverlayTag_4.setBodyContent(_jsp_endTagHack19);
          out.write(_jsp_string3, 0, _jsp_string3.length);
          com.caucho.jsp.BodyContentImpl _jsp_endTagHack22 = null;
          if (_jsp_ImageTag_5 == null) {
            _jsp_ImageTag_5 = new org.apache.taglibs.image.ImageTag();
            _jsp_ImageTag_5.setPageContext(pageContext);
            _jsp_ImageTag_5.setParent((javax.servlet.jsp.tagext.Tag) _jsp_OverlayTag_4);
            _jsp_ImageTag_5.setSrc("/cl_logo.gif");
          }

          int _jspEval24 = _jsp_ImageTag_5.doStartTag();
          if (_jspEval24 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
            out = pageContext.pushBody();
            _jsp_endTagHack22 = (com.caucho.jsp.BodyContentImpl) out;
            _jsp_ImageTag_5.setBodyContent(_jsp_endTagHack22);
            out.write(_jsp_string3, 0, _jsp_string3.length);
            if (_jsp_ResizeTag_6 == null) {
              _jsp_ResizeTag_6 = new org.apache.taglibs.image.ResizeTag();
              _jsp_ResizeTag_6.setPageContext(pageContext);
              _jsp_ResizeTag_6.setParent((javax.servlet.jsp.tagext.Tag) _jsp_ImageTag_5);
              _jsp_ResizeTag_6.setScale("60%");
            }

            _jsp_ResizeTag_6.doEndTag();
            out.write(_jsp_string3, 0, _jsp_string3.length);
            _jsp_ImageTag_5.doAfterBody();
            out = pageContext.popBody();
          }
          _jsp_ImageTag_5.doEndTag();
          if (_jsp_endTagHack22 != null) {
            pageContext.releaseBody(_jsp_endTagHack22);
            _jsp_endTagHack22 = null;
          }
          out.write(_jsp_string7, 0, _jsp_string7.length);
          _jsp_OverlayTag_4.doAfterBody();
          out = pageContext.popBody();
        }
        _jsp_OverlayTag_4.doEndTag();
        if (_jsp_endTagHack19 != null) {
          pageContext.releaseBody(_jsp_endTagHack19);
          _jsp_endTagHack19 = null;
        }
        out.write(_jsp_string6, 0, _jsp_string6.length);
        _jsp_ImageTag_0.doAfterBody();
        out = pageContext.popBody();
      }
      _jsp_ImageTag_0.doEndTag();
      if (_jsp_endTagHack12 != null) {
        pageContext.releaseBody(_jsp_endTagHack12);
        _jsp_endTagHack12 = null;
      }
      out.write(_jsp_string8, 0, _jsp_string8.length);
      com.caucho.jsp.BodyContentImpl _jsp_endTagHack32 = null;
      if (_jsp_ImageTag_7 == null) {
        _jsp_ImageTag_7 = new org.apache.taglibs.image.ImageTag();
        _jsp_ImageTag_7.setPageContext(pageContext);
        _jsp_ImageTag_7.setParent((javax.servlet.jsp.tagext.Tag) null);
        _jsp_ImageTag_7.setSrc("/miku1.jpg");
        _jsp_ImageTag_7.setDir("generated");
        _jsp_ImageTag_7.setName("new-miku-01.jpg");
        _jsp_ImageTag_7.setRefresh(true);
        _jsp_ImageTag_7.setAttributes("border='0' alt='a sample dynamic image'");
      }

      int _jspEval34 = _jsp_ImageTag_7.doStartTag();
      if (_jspEval34 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        out = pageContext.pushBody();
        _jsp_endTagHack32 = (com.caucho.jsp.BodyContentImpl) out;
        _jsp_ImageTag_7.setBodyContent(_jsp_endTagHack32);
        out.write(_jsp_string1, 0, _jsp_string1.length);
        if (_jsp_ResizeTag_8 == null) {
          _jsp_ResizeTag_8 = new org.apache.taglibs.image.ResizeTag();
          _jsp_ResizeTag_8.setPageContext(pageContext);
          _jsp_ResizeTag_8.setParent((javax.servlet.jsp.tagext.Tag) _jsp_ImageTag_7);
          _jsp_ResizeTag_8.setScale("5%");
        }

        _jsp_ResizeTag_8.doEndTag();
        out.write(_jsp_string2, 0, _jsp_string2.length);
        if (_jsp_TextTag_9 == null) {
          _jsp_TextTag_9 = new org.apache.taglibs.image.TextTag();
          _jsp_TextTag_9.setPageContext(pageContext);
          _jsp_TextTag_9.setParent((javax.servlet.jsp.tagext.Tag) _jsp_ImageTag_7);
          _jsp_TextTag_9.setText("Shree ");
          _jsp_TextTag_9.setX("10%");
          _jsp_TextTag_9.setY("75%");
          _jsp_TextTag_9.setFont("Arial");
          _jsp_TextTag_9.setBold(true);
          _jsp_TextTag_9.setSize(10);
          _jsp_TextTag_9.setColor("0x0000ff");
        }

          _jsp_TextTag_9.setBodyContent((javax.servlet.jsp.tagext.BodyContent) null);
        _jsp_TextTag_9.doEndTag();
        out.write(_jsp_string3, 0, _jsp_string3.length);
        _jsp_ImageTag_7.doAfterBody();
        out = pageContext.popBody();
      }
      _jsp_ImageTag_7.doEndTag();
      if (_jsp_endTagHack32 != null) {
        pageContext.releaseBody(_jsp_endTagHack32);
        _jsp_endTagHack32 = null;
      }
      out.write(_jsp_string9, 0, _jsp_string9.length);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      if (_jsp_ImageTag_0 != null)
        _jsp_ImageTag_0.release();
      if (_jsp_ResizeTag_1 != null)
        _jsp_ResizeTag_1.release();
      if (_jsp_TextTag_2 != null)
        _jsp_TextTag_2.release();
      if (_jsp_ResizeTag_3 != null)
        _jsp_ResizeTag_3.release();
      if (_jsp_OverlayTag_4 != null)
        _jsp_OverlayTag_4.release();
      if (_jsp_ImageTag_5 != null)
        _jsp_ImageTag_5.release();
      if (_jsp_ResizeTag_6 != null)
        _jsp_ResizeTag_6.release();
      if (_jsp_ImageTag_7 != null)
        _jsp_ImageTag_7.release();
      if (_jsp_ResizeTag_8 != null)
        _jsp_ResizeTag_8.release();
      if (_jsp_TextTag_9 != null)
        _jsp_TextTag_9.release();
      com.caucho.jsp.QJspFactory.freePageContext(pageContext);
    }
  }

  private com.caucho.java.LineMap _caucho_line_map;
  private java.util.ArrayList _caucho_depends = new java.util.ArrayList();

  public java.util.ArrayList _caucho_getDependList()
  {
    return _caucho_depends;
  }

  public void _caucho_addDepend(com.caucho.make.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    _caucho_depends.add(depend);
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;
    if (com.caucho.util.CauchoSystem.getVersionId() != 1174304630)
      return true;
    for (int i = _caucho_depends.size() - 1; i >= 0; i--) {
      com.caucho.make.Dependency depend;
      depend = (com.caucho.make.Dependency) _caucho_depends.get(i);
      if (depend.isModified())
        return true;
    }
    return false;
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public com.caucho.java.LineMap _caucho_getLineMap()
  {
    return _caucho_line_map;
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
  }

  public void init(com.caucho.java.LineMap lineMap,
                   com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    _caucho_line_map = new com.caucho.java.LineMap("_image__jsp.java", "foo");
    _caucho_line_map.add("/image.jsp", 7, 38);
    _caucho_line_map.add(13, 57);
    _caucho_line_map.add(13, 65);
    _caucho_line_map.add(14, 67);
    _caucho_line_map.add(21, 81);
    _caucho_line_map.add(22, 83);
    _caucho_line_map.add(22, 86);
    _caucho_line_map.add(23, 92);
    _caucho_line_map.add(38, 105);
    _caucho_line_map.add(44, 124);
    _caucho_line_map.add(44, 131);
    _caucho_line_map.add(46, 133);
    _caucho_line_map.add(47, 150);
    _caucho_line_map.add(48, 164);
    _caucho_line_map.add(48, 171);
    _caucho_line_map.add(49, 173);
    _caucho_line_map.add(49, 176);
    _caucho_line_map.add(50, 182);
    _caucho_line_map.add(50, 185);
    _caucho_line_map.add(52, 191);
    _caucho_line_map.add(52, 194);
    _caucho_line_map.add(58, 200);
    _caucho_line_map.add(63, 218);
    _caucho_line_map.add(63, 225);
    _caucho_line_map.add(64, 227);
    _caucho_line_map.add(71, 241);
    _caucho_line_map.add(72, 243);
    _caucho_line_map.add(72, 246);
    _caucho_line_map.add(72, 252);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("image.jsp"), "kKTCZXub18ylSOVy+A6I4Q==", false);
    _caucho_depends.add(depend);
  }

  private final static char []_jsp_string4;
  private final static char []_jsp_string9;
  private final static char []_jsp_string0;
  private final static char []_jsp_string8;
  private final static char []_jsp_string2;
  private final static char []_jsp_string5;
  private final static char []_jsp_string6;
  private final static char []_jsp_string7;
  private final static char []_jsp_string1;
  private final static char []_jsp_string3;
  static {
    _jsp_string4 = " \r\n".toCharArray();
    _jsp_string9 = " \r\n\r\n</td>\r\n</tr>\r\n</table>\r\n\r\n<p align=\"center\">\r\n	<b>Source Images used in the above example:-</b><br/>\r\n	<img src=\"miku1.jpg\" /><br/><br/>\r\n\r\n</p>\r\n\r\n			    	\r\n".toCharArray();
    _jsp_string0 = "\r\n\r\n\r\n<table>\r\n<tr>\r\n<td>\r\n".toCharArray();
    _jsp_string8 = " \r\n\r\n</td>\r\n\r\n<td>\r\n\r\n".toCharArray();
    _jsp_string2 = "\r\n	".toCharArray();
    _jsp_string5 = "\n</td>\r\n<td>\r\n\r\n".toCharArray();
    _jsp_string6 = "\r\n\r\n".toCharArray();
    _jsp_string7 = "  \r\n".toCharArray();
    _jsp_string1 = "\r\n  ".toCharArray();
    _jsp_string3 = "\r\n".toCharArray();
  }
}
