document.write("<table width='780' border='0' align='center' cellpadding='0' cellspacing='0'>");
document.write("<tr>");
document.write("<td width='1' align='left' valign='top' bgcolor='#E0E0E0'><img src='/ananda/img/green_dot.gif' width='1' height='1' /></td>");
document.write("<td align='left' valign='top'>");
document.write("<table width='100%' border='0' cellspacing='0' cellpadding='0'>");
document.write("<tr>");
document.write("<td align='left' valign='top'><a href='/ananda/common/learner/learner.html'><img src='/ananda/img/learner_inside.gif' width='174' height='57' border='0' /></a></td>");
document.write("<td width='1' align='left' valign='top'><img src='/ananda/img/1x1.gif' width='1' height='1' /></td>");
document.write("<td align='left' valign='top'><a href='/ananda/common/curriculum/curriculum.html'><img src='/ananda/img/curriculum_inside.gif' width='174' height='57' border='0' /></a></td>");
document.write("<td width='1' align='left' valign='top'><img src='/ananda/img/1x1.gif' width='1' height='1' /></td>");
document.write("<td align='left' valign='top'><a href='/ananda/common/parents/parents.html'><img src='/ananda/img/parents_inside.gif' width='174' height='57' border='0' /></a></td>");
document.write("<td width='1' align='left' valign='top'><img src='/ananda/img/1x1.gif' width='1' height='1' /></td>");
document.write("<td align='left' valign='top'><a href='/ananda/common/mentor/mentor.html'><img src='/ananda/img/mentor_inside.gif' width='174' height='57' border='0' /></a></td>");
document.write("<td width='1' align='left' valign='top'><img src='/ananda/img/1x1.gif' width='1' height='1' /></td>");
document.write("<td align='left' valign='top'><img src='/ananda/img/home_logo.gif' width='79' height='57' border='0' usemap='#Map' /></td>");
document.write("</tr>");
document.write("</table></td>");
document.write("<td width='1' align='left' valign='top' bgcolor='#E0E0E0'><img src='/ananda/img/green_dot.gif' width='1' height='1' /></td>");
document.write("</tr>");
document.write("</table>");
document.write("<map name='Map' id='Map'>");
document.write("<area shape='rect' coords='20,10,60,48' href='/ananda/index.html' />");
document.write("</map>");