document.write("<table width=\"21%\" bgcolor=\"DFE1BC\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" align=\"left\">");
document.write("<tr bgcolor=\"#FFFFFF\">");
document.write("<td colspan=\"3\" ><img src=\"img/blank.gif\" height=\"3\"></td>");
document.write("</tr>");
document.write("<tr> ");
document.write("<td colspan=\"3\" height=\"100\"><img src=\"img/blank.gif\" height=\"10\"></td>");
document.write("</tr>");
document.write("<tr valign=\"middle\" align=\"left\"> ");
document.write("<td  colspan=\"3\">");
document.write("<table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" align=\"center\"><tr>");
document.write("<td width=\"16%\">&nbsp;</td>");
document.write("<td align=\"left\"><font class=\"lnkblubld\">your page</font></td>");
document.write("</tr>");
document.write("</table>");
document.write("</td>");
document.write("</tr>");
document.write("<tr valign=\"middle\" align=\"left\"> ");
document.write("<td >&nbsp;</td>");
document.write("<td  align=\"left\" valign=\"bottom\" width=\"5\">&nbsp;</td>");
document.write("<td  align=\"left\" valign=\"bottom\">&nbsp;</td>");
document.write("</tr>");
document.write("<tr valign=\"middle\" align=\"left\"> ");
document.write("<td >&nbsp;</td>");
document.write("<td  align=\"left\" valign=\"bottom\" width=\"5\">&nbsp;</td>");
document.write("<td  align=\"left\" valign=\"bottom\"><img src=\"/sis/student/img/flower.gif\" align=\"absmiddle\"></td>");
document.write("</tr>");
document.write("<tr valign=\"middle\" align=\"left\"> ");
document.write("<td  width=\"17\" height=\"8\"><img src=\"img/blank.gif\" width=\"10\" height=\"8\"></td>");
document.write("<td  valign=\"top\" colspan=\"2\"><img src=\"img/blank.gif\" width=\"10\" height=\"8\"></td>");
document.write("</tr>");
document.write("<tr valign=\"middle\" align=\"left\"> ");
document.write("<td  width=\"17\">&nbsp;</td>");
document.write("<td  valign=\"top\" colspan=\"2\"><font class=\"lnkblubld\"><a href=\"/msg/MSGInbox.jsp\">Go to Inbox</a></font></td>");
document.write("</tr>");
document.write("<tr valign=\"middle\" align=\"left\"> ");
document.write("<td  width=\"17\">&nbsp;</td>");
document.write("<td  valign=\"top\" colspan=\"2\"><font class=\"lnkblubld\"><a href=\"/msg/MSGStudentCompose.jsp\">Compose Message</a></font></td>");
document.write("</tr>");
document.write("<tr valign=\"middle\" align=\"left\"> ");
document.write("<td  width=\"17\">&nbsp;</td>");
document.write("<td  valign=\"top\" colspan=\"2\"><font class=\"lnkblubld\"><a href=\"/msg/MSGChannels.jsp\">Choose Your Channels</a></font></td>");
document.write("</tr>");
document.write("<tr> ");
document.write("<td  width=\"17\">&nbsp;</td>");
document.write("<td  height=\"450\" valign=\"top\" align=\"left\" colspan=\"2\">&nbsp;</td>");
document.write("</tr>");
document.write("</table>");

