document.write("<table width=\"100%\" bgcolor=\"DFE1BC\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" align=\"left\">");
document.write("<tr bgcolor=\"#FFFFFF\">");
document.write("<td colspan=\"3\" ><img src=\"/msg/img/blank.gif\" height=\"3\"></td>");
document.write("</tr>");
document.write("<tr valign=\"middle\" align=\"left\"> ");
document.write("<td  width=\"17\" height=\"8\"><img src=\"/msg/img/blank.gif\" width=\"10\" height=\"8\"></td>");
document.write("<td  valign=\"top\" colspan=\"2\"><img src=\"/msg/img/blank.gif\" width=\"10\" height=\"8\"></td>");
document.write("</tr>");
document.write("<tr valign=\"middle\" align=\"left\"> ");
document.write("<td  width=\"17\">&nbsp;</td>");
document.write("<td  valign=\"top\" colspan=\"2\"><a href=\"/msg/MSGInbox.jsp?cat=1\" class=\"lnkbld\">Go to Inbox</a></td>");
document.write("</tr>");
document.write("<tr valign=\"middle\" align=\"left\"> ");
document.write("<td  width=\"17\">&nbsp;</td>");
document.write("<td  valign=\"top\" colspan=\"2\"><a href=\"/msg/MSGStaffCompose.jsp\"  class=\"lnkbld\">Compose Message</a></td>");
document.write("</tr>");
document.write("<tr valign=\"middle\" align=\"left\"> ");
document.write("<td  width=\"17\">&nbsp;</td>");
document.write("<td  valign=\"top\" colspan=\"2\"><a href=\"/msg/MSGChannels.jsp?cat=1\"  class=\"lnkbld\">Choose Channels</a></td>");
document.write("</tr>");
document.write("<tr valign=\"middle\" align=\"left\"> ");
document.write("<td  width=\"17\">&nbsp;</td>");
document.write("<td  valign=\"top\" colspan=\"2\"><a href=\"/msg/MSGManual.jsp?cat=1\"  class=\"lnkbld\">About CLMS</a></td>");
document.write("</tr>");
document.write("<tr> ");
document.write("<td colspan=\"3\" height=\"20\"><img src=\"/msg/img/blank.gif\" height=\"10\"></td>");
document.write("</tr>");
//document.write("<tr> ");
//document.write("<td  width=\"17\">&nbsp;</td>");
//document.write("<td  height=\"700\" valign=\"top\" align=\"left\" colspan=\"2\">&nbsp;</td>");
//document.write("</tr>");
//document.write("</table>");

